### ISSUE TITLE
Use non-breaking space in 'HITsz LUG'

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#10]
As in the title.

HTML example:
```html
HITsz&nbsp;LUG
```

**Comment by Origami404** [comment]
But that will mess up the article and make it ugly. I don't think the weekly need to be such formal, maybe it's a good idea to force it on wiki instead of weekly.

**Comment by h0gan1ee** [comment]
> But that will mess up the article and make it ugly. I don't think the weekly need to be such formal, maybe it's a good idea to force it on wiki instead of weekly. 

Not really in article. However, considering user may copy text from footer or header, I think non-breaking space will cause some troubles.
