### ISSUE TITLE
Remove unnecessary whitespaces around hyperlinks

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#11]
![IMG_20220313_111042.jpg](https://user-images.githubusercontent.com/39949564/158043336-5436b869-8008-4e35-a87a-fa159874850d.jpg)

For example, it would be better if there's no whitespace between Chinese characters.

And more...

**Comment by shirok1** [comment]
<https://github.com/sparanoid/chinese-copywriting-guidelines#%E8%B6%85%E9%80%A3%E7%B5%90%E4%B9%8B%E9%96%93%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC>

**Comment by h0gan1ee** [comment]
> <https://github.com/sparanoid/chinese-copywriting-guidelines#%E8%B6%85%E9%80%A3%E7%B5%90%E4%B9%8B%E9%96%93%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC>

我认为超链接中的元素作为句子成分的一部分，不应该被隔开。比如说：[我们](https://example.com)是一个非营利性组织。

**Comment by Origami404** [comment]
I don't think it's a problem -- nobody will notice it :D

**Comment by shirok1** [comment]
> > https://github.com/sparanoid/chinese-copywriting-guidelines#%E8%B6%85%E9%80%A3%E7%B5%90%E4%B9%8B%E9%96%93%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC
> 
> 我认为超链接中的元素作为句子成分的一部分，不应该被隔开。比如说：[我们](https://example.com)是一个非营利性组织。

这属于是滥用超链接了…… :fearful:

**Comment by h0gan1ee** [comment]
> > > https://github.com/sparanoid/chinese-copywriting-guidelines#%E8%B6%85%E9%80%A3%E7%B5%90%E4%B9%8B%E9%96%93%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC
> > 
> > 我认为超链接中的元素作为句子成分的一部分，不应该被隔开。比如说：[我们](https://example.com)是一个非营利性组织。
> 
> 这属于是滥用超链接了…… :fearful: 

How about Wikipedia.

**Comment by h0gan1ee** [comment]
No further discussion. Closed.
