### ISSUE TITLE
Add algolia search

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#12]
Algolia search is a function provided by theme.

**Comment by SoraShu** [comment]
I don't think 'weekly' needs a search function. And algolia offers limited search capabilities.

**Comment by h0gan1ee** [comment]
Just in case.

Also a search bar can make the web page less boring.

**Comment by Origami404** [comment]
I don't think it's necessary. People could just clone this repo and use any tool (such as VSC) they want to search over all the articles -- or even use Github's code server (just press the `.` in repo frontpage).
