### ISSUE TITLE
Turn on the comment or not ?

### ISSUE THREAD

**Issue by SoraShu** [hitszlug/weekly#13]
> To allow readers to comment under your articles, you can use either Commento, Disqus, Giscus, or Utterances. 

We can use Giscus, which is base on github discussion.

**Comment by h0gan1ee** [comment]
However, that means we must do censorship manually or automatically.

So it there any censorship solutions?

**Comment by Origami404** [comment]
I don't think comments are necessary. If anyone want to say anything, he/she can open an issue in this repo.

**Comment by h0gan1ee** [comment]
Maybe we can give it a shot.

**Comment by Origami404** [comment]
那就试试吧, 整一个基于 GitHub issue 的

**Comment by SoraShu** [comment]
主题内置一个基于discussion的，用那个好。

**Comment by h0gan1ee** [comment]
on 了没

**Comment by Origami404** [comment]
> on 了没

没有, 开了试一下吧

**Comment by h0gan1ee** [comment]
Giscus is unusable due to unresolvable CORS configuration problem. Closed.
