### ISSUE TITLE
week-2 content solicitation

### ISSUE THREAD

**Issue by SoraShu** [hitszlug/weekly#16]
第二周周报内容征集。

目前暂定模块为：

1. 本周群聊
2. 本周旧闻慢递
3. 本周奇怪bug

若有补充直接跟楼

**Comment by yukkodesu** [comment]
![屏幕截图](https://user-images.githubusercontent.com/17264509/158553639-3a0d0250-11ac-450e-a2eb-6a5962c44d7a.png)
B站某些视频视频码率比音频还低

**Comment by SoraShu** [comment]
markdown shebang
![SZ4{BN(H{@S(Z3NJ@WH}L%Q](https://user-images.githubusercontent.com/73573254/158622078-0b426747-fa6a-4e2d-968a-4a0d8cf418c3.jpg)

**Comment by Origami404** [comment]
## 奇怪的 Bug

### WSL 里的 Hugo 预览不了?

试试把端口改成一万以上.

### 雨课堂比油管耗电

在某群友的 Chromebook 上, 虽然都是开网页放视频, 但雨课堂耗电的速度不知道为什么快了一些.

### Miniflux 配 Wallabag 的奇妙行为

> Miniflux 是一个可以自建的 RSS 拉取服务器, Go 编写, 极简主义

> Wallabag 是一个可以自建的书签管理与网页保存器, 可以作为 Pocket 的替代品

在 Miniflux 里填了自建 Wallabag 的 URL 后, Miniflux 会 **先做 DNS** 得到 IP 地址, 然后直接往 IP 地址发包, 导致基于子域名的反代无法工作. 最后直接给 Miniflux 填了处在同一个 Docker Network 里 Wallabag 容器的地址完事. 

### Firefox 又有 Bug

某群友:
> Firefox 不支持 woff2，而且在 Linux 下对于中文的 fallback 有问题。
> 
> 准确来说是非 open type 的 woff2

## 旧闻慢递

### Apple 推出 "格局打开" Emoji

然而在 安卓/win 上都是 口口口.

![图片](https://user-images.githubusercontent.com/29816865/158721096-3a104371-e607-4db3-8883-3353412cd74c.png)

### LUG Sticker 上新

越发离谱的 LGTM.

> LGTM: Look Good To Me, 一般用在 GitHub 的 PR 请求评论里, 表示 approve 别人的 PR

![离谱](https://n.hopp.top/lgtm-s.svg)

### Wiki 上新

新增了一篇介绍域名与 HTTPS 与服务管理的文章: [域名与 HTTPS](https://wiki.hitsz.org/popular-science/domain-and-https/)


### 喜报: 你校数据结构课程有 OJ 辣

好.

~~然而考试还是要手写代码~~

### OpenSSL 远程执行漏洞

计算模平方根的 `BN_mod_sqrt()` 包含 bug 会导致无限循环，它能用于发动拒绝服务攻击。

OpenSSL 3.0.2 跟 1.1.1n 修复了该漏洞.


## 趣事与暴论

### 安卓内核版本之谜

原来 Android 的 Linux kernel 版本是跟 SoC 绑定的. 比如 855 就是 4.14, 865 就是 4.19.

### 群友锐评 IM

> 真正的聊天软件要做减法.
> 
> 我觉得 Socket 就非常适合做 IM, 它非常地通用, 并且可以传递任何信息, 还是即时的.
> 
> IM 不是即时通讯吗, 那能即时通讯的就是 IM.

### 群友锐评 GitHub Action

> 这玩意就是一个写起来很奇怪的服务器


## 这周看了啥

### 代码优化卷翻天：莫队交易赛复盘

是的, 就是 oi 里的 "莫队", 莫涛, 曾经的国家队队长, 举行了一场模拟高频交易的比赛. [这篇知乎文章](https://zhuanlan.zhihu.com/p/470766162)介绍了作者, 一位系统工程师的参赛经历与赛后思考.

### 原来这才是 Socket!

一篇介绍 Socket 的[微信文章](https://mp.weixin.qq.com/s/Syee1T7JcnqACs5TJf-cLA).

### 如何有理有据地说服其他程序员

这篇[博客](https://chinese.catchen.me/2021/06/how-to-argue-with-another-programmer.html)介绍了程序员开发工作中沟通的常见问题与解决方案.

> **TL;DR** 当两个相对聪明和胜任的程序员对同一个问题持有截然不同的观点时，往往问题出现在大家对问题的定义不一样。争辩观点对错的往往并不能达成一致，这时候必须先确认大家在讨论的是同一个问题。如果没办法对齐（align）问题，尤其是当双方的优先级（priority）不一致时，争辩问题的解决方案是不可能有结果的。

### 开源社区的暗面

最近被广泛使用的前端包 `node-ipc` 被发现加入了疑似恶意的功能: 当检测到用户 IP 地址在俄罗斯/白俄罗斯时, 有概率覆写用户的文件. 在正常情况还会在用户的桌面/OneDrive创建特殊的文件, [详情可见 v2ex](https://www.v2ex.com/t/840562). 

之前, 著名前端包 faker.js 作者愤然删库, 抗议大公司白嫖其项目. 

世界上没有绝对好的东西, 这篇[博客](http://qingbob.com/darkside-of-the-opensource/)里作者反思了目前开源的各种问题.

> 某群友: 所以还是 **自由软件** 香

### 如何使用 Shell

这篇[博客](https://a-wing.top/shell/2021/05/01/sh-compatibles-history.html)介绍了 *nix 上各种各样的 Shell 的历史跟特性, 并且在最后简介了他自己的 Shell 配置.

**Comment by eastonman** [comment]
接上周，ctags还在
<img width="727" alt="Screen Shot 2022-03-17 at 16 33 41" src="https://user-images.githubusercontent.com/19954398/158769580-c209065e-60b5-4139-b757-8804108e2a11.png">

**Comment by eastonman** [comment]
- [Systemd service hardening](https://www.ctrl.blog/entry/systemd-service-hardening.html)
- [Best practice to deply Minio](https://blog.min.io/best-practices-minio-virtualized/)
- [A C compiler written in Zig](https://github.com/Vexu/arocc)
