### ISSUE TITLE
Cache dependencies in 'picture generation' action

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#21]
More info: https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

**Comment by shirok1** [comment]
这个可能主题 repo 要用（比如像 gh-page 那样专门一个分支来存放构建后的 static），但这里是用不上的。据我对我图片生成的场景的了解，没有什么东西缓存能比直接下快一大截。

**Comment by shirok1** [comment]
这个可能主题 repo 要用（比如像 gh-page 那样专门一个分支来存放构建后的 static），但这里是用不上的。据我对我图片生成的场景的了解，没有什么东西缓存能比直接下快一大截。

**Comment by h0gan1ee** [comment]
> 这个可能主题 repo 要用（比如像 gh-page 那样专门一个分支来存放构建后的 static），但这里是用不上的。据我对我图片生成的场景的了解，没有什么东西缓存能比直接下快一大截。

How about putting the infamous overweight `node_modules` in the repository?

**Comment by h0gan1ee** [comment]
Or consider using this M$ GitHub action: https://github.com/marketplace/actions/run-playwright-tests

It looks pretty neat. There are also many other options.

**Comment by h0gan1ee** [comment]
Never mind.
