### ISSUE TITLE
Use shorten URL in generated picture

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#23]
Such as:
[weekly.hitsz.org/article/week-2](https://weekly.hitsz.org/article/week-2/) vs [w.lug.pub/2](https://w.lug.pub/2)

**Comment by shirok1** [comment]
草，这个要改动主题吧

**Comment by h0gan1ee** [comment]
> 草，这个要改动主题吧

You can modified the text using JavaScript.

**Comment by h0gan1ee** [comment]
such as:
<img width="416" alt="Screen Shot 2022-03-20 at 17 58 15" src="https://user-images.githubusercontent.com/39949564/159157147-9211551f-4f1d-4a11-8be6-ea43bf26cb39.png">

**Comment by shirok1** [comment]
所以目标是减小二维码的信息量？

**Comment by h0gan1ee** [comment]
> 所以目标是减小二维码的信息量？

It's up to you.

For example:
```
访问 w.lug.pub/2 阅读本文
或扫描如下二维码
<QR code>
```

**Comment by shirok1** [comment]
:thinking:

**Comment by shirok1** [comment]
![](https://user-images.githubusercontent.com/12044683/159158329-3415c343-2ca3-452f-b114-4832b7be3705.png)

**Comment by h0gan1ee** [comment]
https://n.hopp.top/lgtm.svg
