### ISSUE TITLE
第三周内容征集

### ISSUE THREAD

**Issue by SoraShu** [hitszlug/weekly#25]
第三周周报内容征集。

模块为：

1.  本周群聊
2.  本周旧闻慢递
3.  本周奇怪bug
4.  这周看了啥

若有图片建议直接贴在这里。

**Comment by h0gan1ee** [comment]
## Asahi Linux 第一个 alpha 版本发布了🎉

**Comment by h0gan1ee** [comment]
## Weekly 增加 Wawei 字体作为 🍎 系字体的 fallback

~~其实是 HarmonyOS Sans 啦😅~~

要怪就怪微软雅黑、文泉驿点阵长得太丑。（其实 Noto Sans 也好不到哪里去）

**Comment by h0gan1ee** [comment]
> ## Weekly 增加 Wawei 字体作为 🍎 系字体的 fallback
> ~其实是 HarmonyOS Sans 啦😅~
> 
> 要怪就怪微软雅黑、文泉驿点阵长得太丑。（其实 Noto Sans 也好不到哪里去）

https://developer.harmonyos.com/cn/docs/design/des-guides/font-0000001157868583

**Comment by shirok1** [comment]
## Firefox Add-ons 对中国（含港澳台）IP 用户屏蔽 uBlock Origin 的下载页面

同样无法访问的还有 AdGuard AdBlocker（收费）、AdNauseam（uBlock 的分叉）。希望安装这些扩展的用户需要手动下载 .xpi 文件安装。

另外，以下广告屏蔽器的页面仍能正常访问：

*   Ghostery（部分功能收费）
*   AdBlocker Ultimate（部分功能收费）

参考：2016 年 9 月 1 日起施行的《互联网广告管理暂行办法》第 16 条：

> 第十六条 互联网广告活动中不得有下列行为：  
> （一）提供或者利用应用程序、硬件等对他人正当经营的广告采取拦截、过滤、覆盖、快进等限制措施；  
> （二）利用网络通路、网络设备、应用程序等破坏正常广告数据传输，篡改或者遮挡他人正当经营的广告，擅自加载广告；

2021 年 11 月 30 日发表的《互联网广告管理办法（公开征求意见稿）》中移除了此条内容。

**Comment by shirok1** [comment]
## Hello World 也能出 Bug？

💧💧💧

**Comment by shirok1** [comment]
## “我发了链接啊”

URL 的终极形式

![](https://user-images.githubusercontent.com/12044683/159487013-5be19cf1-f09c-492e-9711-ee07be0cc670.png)

**Comment by shirok1** [comment]
## 群名又好了

![](file:///C:\Users\Shiroki\AppData\Roaming\Tencent\QQTempSys\W]X7V2UQ_2{X2~3(8CT6KD6.jpg)

**Comment by shirok1** [comment]
## cjs

![](https://user-images.githubusercontent.com/12044683/159487723-810ed947-026d-4746-a150-adbd1d2ed425.png)

**Comment by eastonman** [comment]
# 这周看了啥
- [Hot-code reloading on macOS/arm64 with Zig](http://www.jakubkonka.com/2022/03/16/hcs-zig.html)
- [Beginner's Guide to Linkers](https://www.lurklurk.org/linkers/linkers.html)

**Comment by eastonman** [comment]
## Zotero 6.0
https://www.zotero.org/blog/zotero-6/

**Comment by Origami404** [comment]
### Bash 语法速查表

当你对一项东西有概念, 但是却一下忘记了该如何使用时, 一份速查表是最合适不过了. 这份 [Bash 速查表](https://wsgzao.github.io/post/bash/)基本上涵盖了 Bash 使用与脚本编写的方方面面, 十分符合 "速查" 的宗旨. 初学者亦可用其来检查自己的学习是否完整.

**Comment by Origami404** [comment]
### 终端颜色指南

想知道如何在终端里输出炫酷的颜色? 这篇[知乎文章](https://zhuanlan.zhihu.com/p/184924477)可以告诉你.

**Comment by Origami404** [comment]
## 旧闻慢递

### 稀土掘金编程挑战赛

... 我不好说. [链接](https://juejin.cn/post/7078608381673472014)

![](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/549cc804e6134e76b614e52ad0f97c5f~tplv-k3u1fbpfcp-zoom-in-crop-mark:1304:0:0:0.awebp?)

**Comment by Origami404** [comment]
## 本周群聊

### Vim vs Emacs

貌似群内 Vim 用户数量完胜 Emacs

> ~~群友A: 除了原生vim哪里都用vim了属于是~~

> 群友B: 现在凡是遇到输入框就：wq

**Comment by shirok1** [comment]
艹好多不规范拼写，血压📈

**Comment by hilaolu** [comment]
某群友想格式化U盘被windows气到破防，一怒之下说出暴论
> linux做得这么好都免费，windows做得这么烂微软是不是应该倒贴钱啊！

**Comment by eastonman** [comment]
- [How does NTP work?](https://sookocheff.com/post/time/how-does-ntp-work/)
