### ISSUE TITLE
Short title proposal

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#26]
Should we limit the length of the title to keep it concise, even if it cannot convey the whole idea.

(Just like this issue)

**Comment by Origami404** [comment]
I think it's good.

Titles like this:

> Firefox Add-ons 对中国（含港澳台）IP 用户屏蔽 uBlock Origin 的下载页面

would be too long. I think it's better to change it to this:

> Firefox 不允许中国用户下载知名去广告插件

And all other titles' lengths are just suitable in my opinion.
