### ISSUE TITLE
第四周内容征集

### ISSUE THREAD

**Issue by Origami404** [hitszlug/weekly#27]
第四周周报内容征集。

模块为：

1. 本周群聊
2. 本周旧闻慢递
3. 本周奇怪bug
4. 本周看了啥

若有图片建议直接贴在这里。

**Comment by hilaolu** [comment]
本周看了啥
https://www.sciencedirect.com/science/article/abs/pii/S0020025522001621

**Comment by LittleYe233** [comment]
本周奇怪bug

**Comment by LittleYe233** [comment]
**本周奇怪bug**

按照电路实验课老师的教程在 Windows 下安装了 Cadence 软件，之后发现 git、GnuPG 等的工作目录被定位到 Cadence 根目录下 `SPB_Data` 文件夹。网络上搜索多份 workaround 且修改了疑似被 Cadence “污染”的环境变量无果后，遂生“重新安装 GnuPG”一计。安装后重启，发现工作目录恢复原样，重设 git 的 `gpgprogram` 配置项后也能正常 commit。

**反思:** 虽然问题得以解决，但过程中进行了多个比较关键的操作（包括但不限于修改环境变量、重装软件、重启），难以断定何因素导致和解决了这一问题。另外以前一直对 GNU 系程序如何在 Windows 下实现不够了解，尝试 workaround 时走了不少弯路。

**参考:**
- <https://superuser.com/questions/1153101/why-does-git-complain-that-no-gpg-agent-is-running>
- <https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key>

**Comment by SoraShu** [comment]
conda or pip  + 系统代理 == http 错误 ？
接第一周的讨论。最终证明是 win + python 特有 bug。详见此 [issue](https://github.com/Fndroid/clash_for_windows_pkg/issues/1787)与此[文章](https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html)

**Comment by Origami404** [comment]
![QQ图片20220402115245](https://user-images.githubusercontent.com/29816865/161366104-88b3c9d7-19fa-4d6b-a4d5-01d559307556.jpg)
![QQ图片20220402111847](https://user-images.githubusercontent.com/29816865/161366106-fb5199cc-f705-41dc-9558-310f281e5e70.jpg)

**Comment by SoraShu** [comment]
![image](https://user-images.githubusercontent.com/73573254/161370211-4715a905-aaba-4ace-9144-c3c2939f16e6.png)
