### ISSUE TITLE
第五周周报内容征集

### ISSUE THREAD

**Issue by Origami404** [hitszlug/weekly#32]
第五周周报内容征集。

模块为：

1. 本周群聊
2. 本周旧闻慢递
3. 本周奇怪bug
4. 本周看了啥

若有图片建议直接贴在这里。

**Comment by shirok1** [comment]
Blueberry Fanta (2022-04-08T22:34): 测试以下

**Comment by shirok1** [comment]
Blueberry Fanta (2022/4/8 下午7:54): 请选择要保存的范围，回复最早的一条消息并@我

**Comment by shirok1** [comment]
Blueberry Fanta (2022/4/8 下午11:03): 这有啥用

**Comment by shirok1** [comment]
佚名 (2022/4/8 下午11:06): 看来回复启动时间以外的消息是获取不了名字的

**Comment by shirok1** [comment]
佚名 (2022/4/8 下午11:03): 这有啥用

**Comment by shirok1** [comment]
第一天 (2022/4/8 下午11:03): 草

**Comment by shirok1** [comment]
Arive (2022/4/9 上午12:12): xdm别乱整代购会报备的

**Comment by shirok1** [comment]
大屏看本专用号 (2022/4/9 上午12:32): 保存成功

**Comment by shirok1** [comment]
大屏看本专用号 (2022/4/9 上午12:34): 保存成功

**Comment by shirok1** [comment]
@shirok1 (2022/4/9 上午12:34):  @大屏看本专用号 保存

**Comment by Origami404** [comment]
@shirok1 (2022/4/9 上午10:38): 能用了吗
@Origami404 (2022/4/9 上午10:38): 群历史记录bot测试中

**Comment by Origami404** [comment]
@Origami404 (2022/4/9 上午10:06): java 的 interface 里的方法的默认可见性是不是

**Comment by Origami404** [comment]
@Origami404 (2022/4/9 上午10:42): java 的 interface 里的方法的默认可见性是不是 public 啊

**Comment by Origami404** [comment]
@shirok1 (2022/4/9 上午10:42): 我突然意识到一个问题
@Origami404 (2022/4/9 上午10:43): ?
@shirok1 (2022/4/9 上午10:43): 就是我实际上并没有限定最晚的一条消息
@shirok1 (2022/4/9 上午10:43): 就
@shirok1 (2022/4/9 上午10:44): 我虽然保存了下来，但是查找的时候没用上
@shirok1 (2022/4/9 上午10:44): 正常用法是这样

**Comment by Origami404** [comment]
@eastonman (2022/4/7 下午8:07): 你的史官到底有没有被风控

**Comment by Origami404** [comment]
## 这周看了啥

### 教育对人的改变有多大?

一篇[博文](https://xiaohanyu.me/posts/2017-02-13-about-education/), 讲述了博主如何借助教育改变了他亲弟弟的人生轨迹, 曾经火过一会.

### 互联网还会变好吗？极客精神与 Web 3

晚点团队的一篇[微信文章](https://mp.weixin.qq.com/s?__biz=MzU3Mjk1OTQ0Ng==&mid=2247492429&idx=1&sn=5bca4865c8738c09e7ec2380780ac3db), 介绍了互联网组织方式的演变, 展望了 Web 3

### The Linux Programming Interface

一本大而全的 Linux 与 *nix 系统编程书, 长达 1552 页, 可在 [man7](https://man7.org/tlpi/) 阅读. 作者 [Michael Kerrisk](https://man7.org/mtk/index.html) 是 Linux Man-Page 的活跃维护者, 曾活跃参与内核的用户界面 API 的设计, 文档以及调试.

### 开源运营当论迹不论心

一篇[博文](https://xuanwo.io/reports/2022-13/), 博主对最近 [TDengine](https://github.com/taosdata/TDengine) 开源社区运营中的一些失误发表了自己的观点, 并描述了他心中有效的开源社区运营方式.

**Comment by Origami404** [comment]
@Origami404 (2022/4/9 上午11:15): 上面的表情包都是我登电脑发的
夕暮 (2022/4/9 上午11:16): [动画表情]

**Comment by Origami404** [comment]
![QQ图片20220409195929](https://user-images.githubusercontent.com/29816865/162575867-de9cc7f8-5d30-4362-bd22-38d76e3a83ec.jpg)
![QQ图片20220409204130](https://user-images.githubusercontent.com/29816865/162575869-cb81a363-1563-4d27-8f04-7eef1914c796.png)
![QQ图片20220409204319](https://user-images.githubusercontent.com/29816865/162575870-e685535b-07b1-46d1-a8bc-a38b153dd993.png)
![QQ图片20220409204611](https://user-images.githubusercontent.com/29816865/162575872-2101eab4-4aad-4f72-ab15-7b5254d1d0bc.png)
![QQ图片20220409204956](https://user-images.githubusercontent.com/29816865/162575873-c1ee96fe-eb09-46d0-be6c-e05c53cf7345.jpg)
![QQ图片20220409205115](https://user-images.githubusercontent.com/29816865/162575876-c145cdc3-5232-444e-8a21-e112b75cae11.jpg)
![QQ图片20220409205557](https://user-images.githubusercontent.com/29816865/162575878-40c6dc8a-555d-4dd2-8100-15bb728d5bb0.jpg)
![QQ图片20220409210123](https://user-images.githubusercontent.com/29816865/162575879-b3ed5715-19f5-40ca-8354-2bf4df1b119d.png)
![QQ图片20220409210607](https://user-images.githubusercontent.com/29816865/162575881-8d7d59c9-e257-4cba-8233-94864da1a80c.png)
