### ISSUE TITLE
第六周周报内容征集

### ISSUE THREAD

**Issue by Origami404** [hitszlug/weekly#36]
第六周周报内容征集。

模块为：

1. 本周群聊
2. 本周旧闻慢递
3. 本周奇怪bug
4. 本周看了啥

若有图片建议直接贴在这里。

**Comment by Origami404** [comment]
预留内容: Scoop 使用感想, 开源游戏介绍, 矮人要塞介绍

**Comment by LittleYe233** [comment]
**本周看了啥**

AMIS：<https://github.com/baidu/amis>

由百度团队牵头。前端低代码框架，通过 JSON 配置就能生成各种页面。支持 SDK 和 React 两种方式调用。

一个项目本来想照例手搓前端，奈何精力不足，deadline在即，只能投靠低码框架。

**Comment by Origami404** [comment]
急招体系结构大手子 (2022/4/14 下午12:11): [图片]
@yukkodesu (2022/4/14 下午12:11): [动画表情]
@h0gan1ee (2022/4/14 下午12:11): @1719709679 6

**Comment by Origami404** [comment]
急招体系结构大手子 (2022/4/14 下午4:50): 有无做计算机建筑学的
急招体系结构大手子 (2022/4/14 下午4:50): computer architecture
急招体系结构大手子 (2022/4/14 下午4:50): 你那破copilot就是个统计学方法
@eastonman (2022/4/14 下午4:50): 草[笑哭]
@eastonman (2022/4/14 下午4:51): 计算机建筑学（
急招体系结构大手子 (2022/4/14 下午4:51): 连停机问题都无法解决 你还指望帮你干啥
CH3CHOHCH3 (2022/4/14 下午4:51): 有无计算机土木学
@h0gan1ee (2022/4/14 下午4:54): {"app":"com.tencent.structmsg","config":{"ctime":1649926493,"forward":true,"token":"8b1497d18bcf673955b6d33d882e30a4","type":"normal"},"desc":"新闻","extra":{"app_type":1,"appid":1103188687,"msg_seq":7086380325743967813,"uin":2806471943},"meta":{"news":{"action":"","android_pkg_name":"","app_type":1,"appid":1103188687,"ctime":1649926493,"desc":"Epic Games与乐高打算建立长期合作关系，索尼相信与Epic的合作将高效结…","jumpUrl":"http://mp.weixin.qq.com/s?__biz=MjM5NTc2MDYxMw==&mid=2458437627&idx=2&sn=d9f326d4eeafa0ba4d7770bf5f8a6ec4&chksm=b18ff77186f87e672d0b1c2e1f2e0cb0e9ad298beed03df98c547eee1d6a655601d94941cb79&mpshare=1&scene=23&srcid=0414kUL3wOBnR74eamV5lL4Q&sharer_sharetime=1649926489920&sharer_shareid=0a0e2d69b70573b99ce3daf5804d0427#rd","preview":"https://mmbiz.qlogo.cn/sz_mmbiz_jpg/1UG7KPNHN8EwbSadMVY77EVpGp8jAuia1Hyb3KzhFzMCYqxCooVibrP0JUMa2zL3c84XmiaRu6C99q6m20r3yClng/300?wx_fmt=jpeg&wxfrom=7","source_icon":"https://i.gtimg.cn/open/app_icon/03/18/86/87/1103188687_100_m.png","source_url":"","tag":"微信","title":"索尼和乐高向Epic Games投资20亿美元以协助开拓元宇…","uin":2806471943}},"prompt":"[分享]索尼和乐高向Epic Games投资20亿美元以协助开拓元宇…","ver":"0.0.0.1","view":"news"}

**Comment by Origami404** [comment]
@Origami404 (2022/4/14 下午8:52): shiroki就是二次元
@shirok1 (2022/4/14 下午8:52): 我有一同学表示对车万人物的认知全部来自oi

**Comment by Origami404** [comment]
@Origami404 (2022/4/16 上午12:51): 看来amesome-hitsz应该首先更新博客链接，hit（sz）er blogs list

@SoraShu (2022/4/16 上午12:51): blog.sorashu.tech

**Comment by shirok1** [comment]
@shirok1 (2022/4/17 上午1:55): ![{0BE907BF-799A-C19F-CD07-4BBA9F3F8C7E}.jpg](http://gchat.qpic.cn/gchatpic_new/990389314/973976017-2740210098-0BE907BF799AC19FCD074BBA9F3F8C7E/0?term=2)

**Comment by shirok1** [comment]
@shirok1 (2022/4/17 上午1:55): [[分享]不止 iOS，腾讯 QQ 办公简洁版 TIM Android…](https://www.ithome.com/0/613/413.htm)

**Comment by Origami404** [comment]
@Origami404 (2022/4/17 下午5:13): ![{F01D4C8F-106C-AAF0-C76F-756558C107B3}.jpg](http://gchat.qpic.cn/gchatpic_new/2292225989/811633021-2389921718-F01D4C8F106CAAF0C76F756558C107B3/0?term=2)

**Comment by Origami404** [comment]
@shirok1 (2022/4/17 下午5:16): [[QQ小程序]哔哩哔哩](https://b23.tv/BHBq1Z6?share_medium=android&share_source=qq&bbid=XXB6A8AB9ACCED3756228179B9CA1F787A9F5&ts=1650187011594)
@shirok1 (2022/4/17 下午5:17): 草
@shirok1 (2022/4/17 下午5:17): 为什么手机上不能回复
@SoraShu (2022/4/17 下午5:17): 草
@SoraShu (2022/4/17 下午5:17): 还真转化成功了
@shirok1 (2022/4/17 下午5:17): ![{134152B5-A82B-7572-BBDB-BBCD75E5249F}.jpg](http://gchat.qpic.cn/gchatpic_new/990389314/811633021-3074622214-134152B5A82B7572BBDBBBCD75E5249F/0?term=2)
@shirok1 (2022/4/17 下午5:17): wtf
@shirok1 (2022/4/17 下午5:17): 这是什么bug
@SoraShu (2022/4/17 下午5:18): 不是啊
@SoraShu (2022/4/17 下午5:18): 是回复一条消息
@SoraShu (2022/4/17 下午5:18): 然后保存到最新吧
@SoraShu (2022/4/17 下午5:18): 你又改了？

**Comment by Origami404** [comment]
pics
![QQ图片20220417153850](https://user-images.githubusercontent.com/29816865/163715379-14b11ebc-968b-4635-a695-0628e0b5916b.jpg)
![QQ图片20220417154543](https://user-images.githubusercontent.com/29816865/163715380-a11ce6e4-4e9f-45e3-be1d-69c5bd7a33f6.png)
![QQ图片20220417155157](https://user-images.githubusercontent.com/29816865/163715382-dcc05e8d-ff92-4c62-bfb2-0832ec9350b0.jpg)
![QQ图片20220417160805](https://user-images.githubusercontent.com/29816865/163715384-4d8fca32-6771-4498-9014-8854bb16c8a7.jpg)
