### ISSUE TITLE
第七周周报内容征集

### ISSUE THREAD

**Issue by Origami404** [hitszlug/weekly#39]
模块为：

1. 本周群聊
2. 本周旧闻慢递
3. 本周奇怪bug
4. 本周看了啥

若有图片建议直接贴在这里。

**Comment by Origami404** [comment]
预留内容: 同 #36

**Comment by Origami404** [comment]
果蛆-不推荐使用Nushell (2022/4/21 下午12:38): 本周奇怪bug
@shirok1 (2022/4/21 下午12:39): ![{7EE4AE35-072B-45C5-8D32-26B85FA5FC9F}.jpg](http://gchat.qpic.cn/gchatpic_new/990389314/811633021-2324044228-7EE4AE35072B45C58D3226B85FA5FC9F/0?term=2)
果蛆-不推荐使用Nushell (2022/4/21 下午12:39): 某群友无法tim和b站无法连接
@shirok1 (2022/4/21 下午12:39): 这是啥
@shirok1 (2022/4/21 下午12:39): 跳板机？
果蛆-不推荐使用Nushell (2022/4/21 下午12:40): 经查发现是因为tim和b站都有使用非常规端口
VaalaCat (2022/4/21 下午12:40): 堡垒机
VaalaCat (2022/4/21 下午12:40): 给大公司提供权限控制的

**Comment by shirok1** [comment]
@shirok1 (2022/4/21 下午3:04): ![{3846906E-A3DE-D1FA-BBF1-A98C891527FB}.png](http://gchat.qpic.cn/gchatpic_new/990389314/973976017-2951601398-3846906EA3DED1FABBF1A98C891527FB/0?term=2)

**Comment by Origami404** [comment]
![QQ图片20220424210816](https://user-images.githubusercontent.com/29816865/164981188-6d88346a-ed8c-4916-a504-b97e270dc1e1.png)
![QQ图片20220424210824](https://user-images.githubusercontent.com/29816865/164981190-15c21abe-8a45-45fe-9639-f50cec9d7396.jpg)
![QQ图片20220424211754](https://user-images.githubusercontent.com/29816865/164981192-3b4f7f7a-3c95-41cf-a9ae-847365179ee3.png)
