### ISSUE TITLE
第八周周报内容征集

### ISSUE THREAD

**Issue by Origami404** [hitszlug/weekly#42]

**Comment by Origami404** [comment]
计科 lxh (2022/4/25 上午9:32): - base
   - report
     - exp4
   - uml
     - exp4_StrategyPattern.puml

在 exp4 里引用 exp4_StrategyPattern.puml

我现在的写法是
[exp4_StrategyPattern.puml](..\uml\exp4_StrategyPattern.puml)

怎么改捏
@Origami404 (2022/4/25 上午9:35): 这GitHub上不行吗
计科 lxh (2022/4/25 上午9:35): 不行
我要吃飞鱼 (2022/4/25 上午9:35): IDEA的目录结构是从根目录开始的，github会不会读idea配置呢
@Origami404 (2022/4/25 上午9:36): @792972314,  你试试/
@Origami404 (2022/4/25 上午9:36): 会不会是反斜杠不认啊
@Origami404 (2022/4/25 上午9:36): 反正Windows也认/
@yukkodesu (2022/4/25 上午9:36): 为啥面向对象这个要传上github
@yukkodesu (2022/4/25 上午9:37): 我感觉我自己糊的屎估计不会想给别人看
推荐使用Debian (2022/4/25 上午9:37): 是不是gui设计实验？
推荐使用Debian (2022/4/25 上午9:37): [斜眼笑]
@yukkodesu (2022/4/25 上午9:38): 不是吧
推荐使用Debian (2022/4/25 上午9:39): 有个同学亲切地称之为gui设计实验
推荐使用Debian (2022/4/25 上午9:39): [笑哭]
计科 lxh (2022/4/25 上午9:39): @2292225989,  我靠 真是
计科 lxh (2022/4/25 上午9:40): 好吧 现在相对路径的问题解决了
计科 lxh (2022/4/25 上午9:41): 可是本地typora还是没有找到设置以repo根的地方, [撇嘴], 💦💦
@Origami404 (2022/4/25 上午9:43): 我的评价是
@Origami404 (2022/4/25 上午9:43): rtfm
@Origami404 (2022/4/25 上午9:43): ![{C5B3C074-E7C2-2169-CA5C-B70E6869D177}.jpg](http://gchat.qpic.cn/gchatpic_new/2292225989/811633021-2589841343-C5B3C074E7C22169CA5CB70E6869D177/0?term=2)
RMan (2022/4/25 上午9:43): @792972314,  
, ![{8D6699A5-0465-6B2F-79F9-19F00AC89B09}.jpg](http://gchat.qpic.cn/gchatpic_new/740827790/811633021-3116629147-8D6699A504656B2F79F919F00AC89B09/0?term=2), 
这里可以设置根路径
RMan (2022/4/25 上午9:44): ![{E1D6C677-7A75-3C13-DB19-3038D8370159}.jpg](http://gchat.qpic.cn/gchatpic_new/740827790/811633021-2905641188-E1D6C6777A753C13DB193038D8370159/0?term=2)

**Comment by hilaolu** [comment]
Hi guys I 'd recommend a shiny shiny music player I just found to you.
[netease-musicbox](https://github.com/darknessomi/musicbox)

Main features(which i treasure/is important to me)

- Pure CLI
- Very low overhead
- Written in Python
- Netease Cloud Music online streaming
- Rich features, covering most use cases
- Restrict resource support(if you have a VIP account)
- Vim-like interactive and configurable key mapping 

I have been finding such a good player for months.
None but this musicbox satisfies my needs.
This one is ideal for me.



I also recommend easyeffects to you, a powerful compressor under pipewire.
[easyeffects](https://github.com/wwmm/easyeffects)

**Comment by Origami404** [comment]
@Origami404 (2022/4/25 下午10:13): 配了反代之后
@Origami404 (2022/4/25 下午10:14): 访问反代的话
@Origami404 (2022/4/25 下午10:14): 客户端是直接跟上游通讯
@Origami404 (2022/4/25 下午10:14): 还是通过反代跟上游通讯
@eastonman (2022/4/25 下午10:23): 你都说了反代了
@eastonman (2022/4/25 下午10:23): 当然是“代理”通信
@Origami404 (2022/4/25 下午10:31): 懂了
@Origami404 (2022/4/25 下午10:31): 诶不对
@Origami404 (2022/4/25 下午10:32): 那那些什么“用反代实现负载均衡”的
@Origami404 (2022/4/25 下午10:32): 瓶颈岂不是卡在反代服务器带宽上了
@eastonman (2022/4/25 下午10:32): 是
@eastonman (2022/4/25 下午10:32): 但是一般负载均衡的负载不是带宽（
@Origami404 (2022/4/25 下午10:33): 带宽均衡就上cdn了是吧
@eastonman (2022/4/25 下午10:33): 也可以dns round robin
@Origami404 (2022/4/25 下午10:34): 懂了

**Comment by LittleYe233** [comment]
**本周奇怪bug**

以太网下配好密钥的两台机器 `ssh` 时不同连接方向和双方用户会产生不同结果：某些情况可以直接连接，某些情况下连接需要密码，有时甚至输对了密码也会 `Permission denied`。搜索引擎求助未果后论坛提问，终顿悟：删 `~/.ssh/known_hosts` 时误操作把 `~/.ssh/authorized_keys` 删了。

详见：[[SOLVED] ssh keeps asking for password and returns "Permission denied"](https://bbs.archlinux.org/viewtopic.php?id=275912)

**Comment by shirok1** [comment]
Blueberry Fanta (2022/4/27 13:55:32): ![{1DEEAE42-C61E-A357-0874-DB977828A78C}.jpg](http://gchat.qpic.cn/gchatpic_new/990389314/973976017-3117136294-1DEEAE42C61EA3570874DB977828A78C/0?term=2)
Blueberry Fanta (2022/4/27 13:56:59): 测试

**Comment by Origami404** [comment]
![QQ图片20220430231822](https://user-images.githubusercontent.com/29816865/166113458-e778130a-6f85-4796-8879-dfc63de8767d.png)
