### ISSUE TITLE
第九周周报内容征集

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#46]

**Comment by h0gan1ee** [comment]
音乐推荐：
- 作品名：四季
- 作词、作曲、演唱：大貫妙子
- 演奏：坂本龍一
- 流派：当代古典音乐（Contemporary Classical Music)
- 收听链接：<https://music.163.com/#/song?id=633083>、

**Comment by h0gan1ee** [comment]
## Firefox in real life
![IMG_20220504_222443_831.jpg](https://user-images.githubusercontent.com/39949564/166702619-5793b344-95ba-41c7-8fe3-0f7331b4398e.jpg)

**Comment by h0gan1ee** [comment]
# 不推荐使用 Lisp

🈲️lisp

我之前看到

说那撒的火星车就是lisp

他们写出了个bug

然后热重载修好了

**Comment by h0gan1ee** [comment]
## Richard Stallman 呼吁不看疫情报导

https://stallman.org/articles/dont-watch-covid-tv.html

😅

**Comment by h0gan1ee** [comment]
## 最佳 Lua 入门：饥荒 mods

**Comment by h0gan1ee** [comment]
## F# > Elixir

placeholder

**Comment by h0gan1ee** [comment]
## 如何 vanish 飞机

placeholder

**Comment by h0gan1ee** [comment]
## 萝佬是萝莉萝卜

😅

**Comment by h0gan1ee** [comment]
## 手把手带你读论文

https://github.com/papers-we-love/papers-we-love

**Comment by h0gan1ee** [comment]
## Web Feed 倡议书

https://u.sb/lets-web-feed/

**Comment by h0gan1ee** [comment]
## 捍卫自由的互联网，对 Web 3 说不

https://blog.skk.moe/post/keep-web-free-say-no-to-web3/

**Comment by h0gan1ee** [comment]
## 睿站赠送大会员「抗疫守『沪』」

https://www.bilibili.com/blackboard/activity-TuhcQyqcpo.html

**Comment by Origami404** [comment]
![image](https://user-images.githubusercontent.com/29816865/167434078-4c37a969-68ac-4ddb-8862-e141ba2e463e.png)

**Comment by Origami404** [comment]
![QQ图片20220509201439](https://user-images.githubusercontent.com/29816865/167434106-b73d9161-cc60-4bf5-bc07-11dd1fcf10ac.jpg)
<img width="248" alt="QQ图片20220509202800" src="https://user-images.githubusercontent.com/29816865/167434124-814f4b9b-4e0f-48cb-b3f5-d9a9a5224469.png">
![QQ图片20220509203247](https://user-images.githubusercontent.com/29816865/167434141-aa1a91ab-d26d-4e82-bd21-e760a975ad88.png)
![QQ图片20220509203300](https://user-images.githubu
![QQ图片20220509220920](https://user-images.githubusercontent.com/29816865/167434216-4b7f4075-100e-48db-bc7e-372e556a5917.jpg)

![QQ图片20220509203946](https://user-images.githubusercontent.com/29816865/167434196-8099c2c1-473e-4a62-989a-f961218e7fb6.png)

![QQ图片20220509203943](https://user-images.githubusercontent.com/29816865/167434187-c5dd3875-3ba0-47e9-b0de-72175aa7181d.png)
sercontent.com/29816865/167434147-ad987278-33fb-4013-9cb1-cc5c7df17a12.png)

**Comment by Origami404** [comment]
![QQ图片20220509203924](https://user-images.githubusercontent.com/29816865/167436139-e3ad9b95-c0f4-45f1-80ef-84ce4b0e9aa9.jpg)
