### ISSUE TITLE
第十周周报内容征集

### ISSUE THREAD

**Issue by hilaolu** [hitszlug/weekly#48]

**Comment by hilaolu** [comment]
### Wired Character in Java socket output stream
```
import java.net.ServerSocket;
import java.net.Socket;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.io.DataOutputStream;

public class Server {
	public static void main(String[] args) {
		try {

			ServerSocket server_socket = new ServerSocket(11451);
			Socket client_socket = server_socket.accept();
			PrintStream print_output_stream = new PrintStream(new ObjectOutputStream(client_socket.getOutputStream()));
			while (true) {
				print_output_stream.println("hello world");
				print_output_stream.flush();
				Thread.sleep(1145);
			}
		} catch (Exception e) {
			// do nothing
		}
	}
}

```

```
telnet 127.0.0.1 11451
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
��w
   hello world
w
 hello world
w
 hello world
w
 hello world
w
 hello world
```

**Comment by hilaolu** [comment]
### Auto type inferring in java

**Comment by hilaolu** [comment]
音乐推荐：

- 作品名：ゴローンゴローン～フンコロガシ～
- 专辑：?
- 作词 : Nem
- 演唱：[鎖那](https://music.163.com/artist?id=1002089) / [ﾎﾛﾎﾛ鳥](https://music.163.com/artist?id=12131302)
- 作曲：Nem
- 演奏：?
- 专辑流派：?
- 收听链接：https://music.163.com/#/song?id=409941268


**滚啊滚啊 Archlinux**

**Comment by eastonman** [comment]
- [ZFS without a Server Using the NVIDIA BlueField-2 DPU](https://www.servethehome.com/zfs-without-a-server-using-the-nvidia-bluefield-2-dpu-nvme-arm-aic-iscsi/)

**Comment by Origami404** [comment]
![QQ图片20220516215133](https://user-images.githubusercontent.com/29816865/168946513-1acc5042-6032-410d-9209-0169143b54c5.png)
![QQ图片20220516215136](https://user-images.githubusercontent.com/29816865/168946516-a8eff1ec-8dee-40fb-9546-779327be4555.png)
![QQ图片20220516215145](https://user-images.githubusercontent.com/29816865/168946518-8aeabc4a-5cce-4113-afac-041fd066cda5.png)
![QQ图片20220516215148](https://user-images.githubusercontent.com/29816865/168946520-056371b3-b1d3-435a-9658-b981aa0a473c.png)
![QQ图片20220516215154](https://user-images.githubusercontent.com/29816865/168946522-f614ebfd-18b4-4d92-9f6a-c76b5d7ce174.png)
![QQ图片20220516215204](https://user-images.githubusercontent.com/29816865/168946523-b494ed81-c59f-4cc4-8cc0-bbd30493d9ab.png)
![QQ图片20220516215209](https://user-images.githubusercontent.com/29816865/168946527-b65e018e-996c-4482-9c2b-4d87f71a08fa.png)
![QQ图片20220516104816](https://user-images.githubusercontent.com/29816865/168946529-3ad12c75-c813-4683-810b-a276a180b1ee.jpg)
![QQ图片20220516113331](https://user-images.githubusercontent.com/29816865/168946530-3ae2a601-26b1-4734-b73a-9cb7b1d02e91.png)
![QQ图片20220516113335](https://user-images.githubusercontent.com/29816865/168946531-0d8957dc-9e16-40a0-bf7a-7b107db149cc.png)
![QQ图片20220516113405](https://user-images.githubusercontent.com/29816865/168946532-71021fe1-d113-47ec-959c-9be2460a6b0d.jpg)
