### ISSUE TITLE
Use a more concise description

### ISSUE THREAD

**Issue by h0gan1ee** [hitszlug/weekly#9]

**Comment by Origami404** [comment]
What description do you mean? The `About` page?

**Comment by h0gan1ee** [comment]
> What description do you mean? The `About` page?

![IMG_20220313_161834.jpg](https://user-images.githubusercontent.com/39949564/158051232-edec7377-edb0-471a-a967-c05056a770a7.jpg)

Also, this is not an ideal description for search engine crawlers.

**Comment by h0gan1ee** [comment]
Something like '这里记录着 HITSZ LUG 的奇闻轶事' will be sufficient and more preferable.

**Comment by Origami404** [comment]
What about "HITsz LUG 每周奇闻轶事"?

**Comment by h0gan1ee** [comment]
> What about "HITsz LUG 每周奇闻轶事"?

LGTM!
